### ISSUE TITLE
Feature Suggestion: Add Weekly Most Upvoted Posts to the Homepage

### ISSUE THREAD

**Issue by karanagg166** [Poojan38380/i-luv-college#1]
Hi poojan,

First of all, thank you for all the great work you're doing with this project! I had a suggestion that I think could enhance the user experience.

Suggestion:
It would be great to have a "Weekly Most Upvoted Posts" section on the homepage. This feature would allow users to easily see the top posts of the week based on upvotes, promoting more engagement and making it easier to surface high-quality content.

**Comment by Poojan38380** [comment]
Your PR has been accepted and merged
